export enum HeadEnum {
  Name = 'name',
  Tier = 'tier',
  ParentPortfolios = 'parentPortfolios',
  ChildPortfolios = 'childPortfolios',
  PrevailingAssets = 'prevailingAssets',
  PrevailingCountries = 'prevailingCountries',
  PrevailingIndustries = 'prevailingIndustries',
  AssetDescription = 'assetDescription',
  ValueCost = 'valueCost',
  Exposure = 'exposure',
  PL = 'pl',
  Allocation = 'allocation',
  CountryRegion = 'countryRegion',
  IndustrySector = 'industrySector',
  SourceDescription = 'sourceDescription',
  Cost = 'cost',
  SymbolName = 'symbolName',
  Amount = 'amount',
}

export const HEAD_DATA: { [key in HeadEnum]: string } = {
  [HeadEnum.Name]: 'Name',
  [HeadEnum.Tier]: 'Tier',
  [HeadEnum.ParentPortfolios]: 'Parent portfolios',
  [HeadEnum.ChildPortfolios]: 'Child portfolios',
  [HeadEnum.PrevailingAssets]: 'Prevailing assets',
  [HeadEnum.PrevailingCountries]: 'Prevailing countries',
  [HeadEnum.PrevailingIndustries]: 'Prevailing industries',
  [HeadEnum.AssetDescription]: 'AssetDescription',
  [HeadEnum.ValueCost]: 'ValueCost',
  [HeadEnum.Exposure]: 'Exposure',
  [HeadEnum.PL]: 'PL',
  [HeadEnum.Allocation]: 'Allocation',
  [HeadEnum.CountryRegion]: 'Country/Region',
  [HeadEnum.IndustrySector]: 'Industry/Sector',
  [HeadEnum.SourceDescription]: 'Source/Description',
  [HeadEnum.Cost]: 'Cost',
  [HeadEnum.SymbolName]: 'Symbol/Name',
  [HeadEnum.Amount]: 'Amount',
};
